FROM php:8.0-apache
RUN sed -i 's/http:\/\/deb.debian.org/http:\/\/ftp.kr.debian.org/g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y default-mysql-client

# PHP 모듈 설치 (필요한 경우 추가)
RUN docker-php-ext-install mysqli pdo pdo_mysql

# MySQL 클라이언트 설치
RUN apt-get update && apt-get install -y default-mysql-client

# 애플리케이션 파일을 Apache 웹 루트 디렉토리로 복사
#COPY ./ /var/www/html/

# Apache 포트 노출
EXPOSE 80

