# Containerfile.db
FROM docker.io/mysql:8.0
# 데이터베이스 초기화 파일 복사
COPY bluebirdhotel.sql /docker-entrypoint-initdb.d/

# 환경 변수 설정 (MySQL 사용자, 비밀번호, 데이터베이스)
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=bluebirdhotel
ENV MYSQL_USER=bluebird_user
ENV MYSQL_PASSWORD=password

# MySQL 기본 포트 노출
EXPOSE 3306

