apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluebird-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluebird-db
  template:
    metadata:
      labels:
        app: bluebird-db
    spec:
      containers:
        - name: bluebird-db-container
          image: registry.demo.io:5000/php/db:v1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "bluebirdhotel"
            - name: MYSQL_USER
              value: "bluebird_user"
            - name: MYSQL_PASSWORD
              value: "password"
          volumeMounts:
            - name: app-data
              mountPath: /var/lib/mysql
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data

---
apiVersion: v1
kind: Service
metadata:
  name: bluebird-db-service
spec:
  selector:
    app: bluebird-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # headless service for direct access

