apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  labels:
    app: app-data
spec:
  storageClassName: "default"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

