apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluebird-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluebird-web
  template:
    metadata:
      labels:
        app: bluebird-web
    spec:
      containers:
        - name: bluebird-web-container
          image: registry.demo.io:5000/php/web:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bluebird-web-service
spec:
  selector:
    app: bluebird-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
